Revert "Add multi version temp branch (#2)"
This reverts commit 196380bc7b3b8c69cb65a08ec87e3c0fa8e21fee.

diff --git a/.github/workflows/sphinx-make-page.yml b/.github/workflows/sphinx-make-page.yml
--- a/.github/workflows/sphinx-make-page.yml
+++ b/.github/workflows/sphinx-make-page.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - master
   schedule:
-  # Run every morning to ensure component documentation is up to date on deployment
+   # Run every morning to ensure component documentation is up to date on deployment
    - cron: '23 5 * * *'
   pull_request: # only runs up through build of sphinx
 
@@ -13,33 +13,50 @@ jobs:
   build-deploy:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
+    - name: checkout control.ros.org
+      uses: actions/checkout@v2
+    - name: checkout ros2_control
+      uses: actions/checkout@v2
       with:
-        fetch-depth: 0
-    - uses: actions/setup-python@v2
+        repository: ros-controls/ros2_control
+        ref: master
+        path: ros2_control
+    - name: checkout ros2_controllers
+      uses: actions/checkout@v2
       with:
-        python-version: '3.8'
-        cache: 'pip'
-    - name: Install Python dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install --upgrade --requirement requirements.txt
-    - name: Install doxygen and graphviz
-      run: sudo apt-get install -y doxygen graphviz
-    - name: Build multiversion with API
-      run: |
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        make multiversion-with-api
+        repository: ros-controls/ros2_controllers
+        path: ros2_controllers
+    - name: checkout ros2_control_demos
+      uses: actions/checkout@v2
+      with:
+        repository: ros-controls/ros2_control_demos
+        path: ros2_control_demos
+    - name: build sphinx docs 
+      uses: ammaraskar/sphinx-action@master
+      with:
+        docs-folder: "."
+        pre-build-command: "apt-get update --allow-releaseinfo-change && apt-get install -y doxygen graphviz && pip3 install -r requirements.txt"
     - name: clone gh-pages branch
       uses: actions/checkout@v2
-      if: ${{ success() && github.event_name != 'pull_request' && !env.ACT }}
+      if: github.event_name != 'pull_request'
       with:
         ref: gh-pages
         path: gh-pages
-    - name: Deploy Pages
-      if: ${{ success() && github.event_name != 'pull_request' && !env.ACT }}
-      uses: peaceiris/actions-gh-pages@v3
+    - name: Commit documentation changes
+      if: github.event_name != 'pull_request'
+      run: |
+        cp -r _build/html/* gh-pages/
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # the return code.
+    - name: Push changes
+      if: ${{ github.event_name != 'pull_request' && !env.ACT }}
+      uses: ad-m/github-push-action@master
       with:
+        branch: gh-pages
+        directory: gh-pages
         github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: ./_build/html
